[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "yarn"]

[build.nixpacksPlan.phases.install]
command = "yarn install"

[build.nixpacksPlan.phases.build]
command = "yarn build"
